#!/usr/bin/env bash

# formatting
txtblk='\e[0;30m' # Black
txtred='\e[0;31m' # Red
txtgrn='\e[0;32m' # Green
txtylw='\e[0;33m' # Yellow
txtblu='\e[0;34m' # Blue
txtpur='\e[0;35m' # Purple
txtcyn='\e[0;36m' # Cyan
txtwht='\e[0;37m' # White
italic='\e[3m'    # italic
bold='\e[1m'      # bold
reset='\e[0m'     # reset

# get wm name
wm_win_id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
wm_win_id=${wm_win_id##* }
wm=$(xprop -id "$wm_win_id" -notype -len 100 -f _NET_WM_NAME 8t)
wm=${wm/*WM_NAME = /}
wm=${wm/\"/}
wm=${wm/\"*/}

# info
USER=$(whoami)
KERNEL=$(uname -r)
OS=$(cat /etc/os-release | grep "PRETTY_NAME=" | cut -c 13- | tr -d '"')
PKGS=$((dpkg-query -l 2> /dev/null || pacman -Q 2> /dev/null ) | wc -l)
WTTR=$(curl -s https://wttr.in/\?format\=%C+%t)
WM=${wm}
GTK=$(gsettings get org.gnome.desktop.interface gtk-theme |  tr -d "'")
UPTIME=$(uptime -p | cut -d"," -f1)
SHELL="${SHELL##*/}"

# fetch
echo -e "${txtcyn}╭─────────────────────────────────────────────────────────────────────╮"
echo -e "${reset}"
echo -e "${txtred}      ⣀⣤⣴⣶⣶⣦⣄⡀      ⢀⣤⣶⣶⣶⣦⣤⡀      os      :  ${bold}${OS}"
echo -e "${txtred}    ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣷⣄   ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀    kernel  :  ${bold}${KERNEL}"
echo -e "${txtylw}    ⣾⣿⠟⠋⠉  ⠉⠙⠻⣿⣷⡀⣰⣿⣿⣿⠟⠉   ⠈⠙⣿⣷    theme   :  ${bold}${GTK}"
echo -e "${txtylw}   ⢸⣿⠏        ⠈⢻⣿⣿⣿⡿⠃       ⠸⣿⡇   shell   :  ${bold}${SHELL}"
echo -e "${txtwht}   ⢸⣿         ⢀⣾⣿⣿⡿⠁         ⣿⡇   wm      :  ${bold}${WM}"
echo -e "${txtblu}   ⢸⣿⡆       ⢀⣾⣿⣿⣿⣧⡀        ⢰⣿⡇   pkgs    :  ${bold}${PKGS}"
echo -e "${txtblu}    ⢿⣿⣄⡀   ⢀⣴⣿⣿⣿⠟⠘⢿⣿⣦⣀⡀  ⢀⣀⣴⣿⡿    user    :  ${bold}${USER}"
echo -e "${txtpur}    ⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁   ⠙⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁    uptime  :  ${bold}${UPTIME}"
echo -e "${txtpur}      ⠈⠛⠻⠿⠿⠿⠛⠁      ⠈⠙⠻⠿⠿⠿⠛⠉      weather :  ${bold}${WTTR}"
echo -e "${reset}"
echo -e "                          ${txtred}  ${txtgrn}  ${txtylw}  ${txtblu}  ${txtpur}  ${txtcyn}  ${txtwht}                          "
echo -e "${reset}"
echo -e "${txtcyn}╰─────────────────────────────────────────────────────────────────────╯"
